import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const url=Deno.env.get("SUPABASE_URL")??""; const key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";
const db=createClient(url,key,{auth:{persistSession:false}});
const ops=new Set(["admin_verify","admin_list_books","admin_save_book","admin_delete_book","admin_apply_discount","admin_apply_discount_until","admin_clear_discounts","admin_list_orders","admin_list_sales","admin_update_order_status","admin_update_order_tracking","admin_accept_order_with_note","admin_user_stats","admin_list_customers","admin_device_analytics","admin_restock_waitlist","admin_shipping_queue_list","admin_shipping_queue_add","admin_shipping_queue_edit_contact","admin_shipping_queue_dismiss","admin_finance_report","admin_finance_expenses","admin_add_finance_expense","admin_update_finance_expense","admin_delete_finance_expense","admin_set_book_thumbnail","admin_set_preorder_price_max","admin_merchandising_insights","admin_demand_analytics","admin_bundle_list","admin_bundle_save","admin_bundle_delete","admin_store_notice_get","admin_store_notice_save","admin_push_subscriptions","admin_push_subscriptions_for_phone","event_push_subscriptions","event_push_message_log","admin_push_log","admin_push_message_create","admin_push_message_finish","admin_push_history"]);
const origins=new Set(["https://muhajeer-books-live-production.up.railway.app"]);
const rate=new Map<string,{n:number,until:number}>();
function okRate(k:string){const now=Date.now();const v=rate.get(k);if(!v||v.until<=now){rate.set(k,{n:1,until:now+60000});return true}if(v.n>=180)return false;v.n++;return true}
function clientKey(req:Request){return (req.headers.get("x-forwarded-for")??req.headers.get("cf-connecting-ip")??"unknown").split(",")[0].trim()}
function headers(o:string){return {"Content-Type":"application/json","Cache-Control":"no-store","Access-Control-Allow-Origin":origins.has(o)?o:"https://muhajeer-books-live-production.up.railway.app","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"}}
function out(o:string,s:number,b:unknown){return new Response(JSON.stringify(b),{status:s,headers:headers(o)})}
Deno.serve(async req=>{const o=req.headers.get("origin")??"";if(req.method==="OPTIONS"){if(o&&!origins.has(o))return new Response(null,{status:403});return new Response(null,{status:204,headers:headers(o)})}if(req.method!=="POST")return out(o,405,{ok:false,error:"Method not allowed"});if(o&&!origins.has(o))return out(o,403,{ok:false,error:"Origin not allowed"});if(!okRate(clientKey(req)))return out(o,429,{ok:false,error:"Too many requests"});try{const b=await req.json();const n=String(b?.name??"");const p=(b?.params&&typeof b.params==="object")?b.params:{};if(!ops.has(n))return out(o,403,{ok:false,error:"Operation not allowed"});const secretField=(n==="event_push_subscriptions"||n==="event_push_message_log")?"p_event_secret":"p_secret";if(typeof p[secretField]!=="string"||p[secretField].length<1||p[secretField].length>512)return out(o,403,{ok:false,error:"Authorization required"});const {data,error}=await db.rpc(n,p);if(error){console.error("admin-rpc",n,error.code);return out(o,400,{ok:false,error:"Admin operation failed"})}return out(o,200,{ok:true,data})}catch(e){console.error("admin-rpc",e);return out(o,400,{ok:false,error:"Bad request"})}});
